model_list:
  - model_name: semantic-router
    litellm_params:
      model: openai/semantic-router
      api_base: http://gateway-semantic-router-spike:4011/v1
      api_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  drop_params: true

router_settings:
  routing_strategy: simple-shuffle
  request_timeout: 45

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  disable_master_key_return: true
